analytics: {}
color:
  brandColors:
    - '#C0A0A0'
    - '#008840'
    - '#489868'
    - '#B81828'
    - '#000000'
  brandStrength: 0.345395
  lightness: 0.909836
  rhythmicContrast: 0.706566
  saturation: 0.792241
cta: {}
layout_spectrum: 0.36102
name: bazaarparcel
opengraph: {}
purpose: {}
typography_spectrum: 0.29008655851532417
