analytics: {}
color:
  brandColors:
    - '#C0C8C0'
    - '#705008'
    - '#B8A860'
    - '#E0C060'
    - '#E0D8A0'
  brandStrength: 0.345395
  lightness: 0.909836
  rhythmicContrast: 0.706566
  saturation: 0.792241
cta: {}
layout_spectrum: 0.36102
name: bazaarparcel
opengraph: {}
purpose: {}
typography_spectrum: 0.29008655851532417
